import random

interests = ['True Crime', 'Science', 'Comedy', 'Sports', 'Business', 'Technology', 'Society', 'Health', 'Art', 'Music', 'Spirituality']

languages = ["English", "German", "Both"]

user_profiles = [{"user_id": 0, "lang": "German", "interests": ["Science", "Art", "Comedy"] }, 
{"user_id": 1, "lang": "English", "interests": ["True Crime", "Technology", "Comedy"] }, 
{"user_id": 2, "lang": "English", "interests": ["Art", "Health", "Music"] }, 
{"user_id": 3, "lang": "German", "interests": ["Music", "Society"] }, 
{"user_id": 4, "lang": "German", "interests": ["Technology", "Sports", "Society"] }, 
{"user_id": 5, "lang": "English", "interests": ["Technology", "Society"] }, 
{"user_id": 6, "lang": "English", "interests": ["True Crime", "Comedy", "Music"] }, 
{"user_id": 7, "lang": "German", "interests": ["Art", "Spirituality", "Comedy", "Sports"] }, 
{"user_id": 8, "lang": "German", "interests": ["Art", "Science", "Sports", "Music"] }, 
{"user_id": 9, "lang": "Both", "interests": ["Spirituality", "Art"] }, 
{"user_id": 10, "lang": "English", "interests": ["Art", "Comedy", "Science"] }, 
{"user_id": 11, "lang": "English", "interests": ["Comedy", "Spirituality", "Business"] }, 
{"user_id": 12, "lang": "German", "interests": ["Art", "Science", "Society", "Technology"] }, 
{"user_id": 13, "lang": "Both", "interests": ["Technology"] }, 
{"user_id": 14, "lang": "German", "interests": ["Art", "Technology", "Business"] }, 
{"user_id": 15, "lang": "German", "interests": ["Science", "True Crime", "Art"] }, 
{"user_id": 16, "lang": "German", "interests": ["Society"] }, 
{"user_id": 17, "lang": "Both", "interests": ["Comedy", "Spirituality", "Society", "Business"] }, 
{"user_id": 18, "lang": "Both", "interests": ["Art", "Health", "Science"] }, 
{"user_id": 19, "lang": "English", "interests": ["Spirituality", "Sports", "Art", "Society", "True Crime"] }, 
{"user_id": 20, "lang": "Both", "interests": ["Art"] }, 
{"user_id": 21, "lang": "German", "interests": ["Business", "Comedy", "Health"] }, 
{"user_id": 22, "lang": "Both", "interests": ["Business", "Society", "Science"] }, 
{"user_id": 23, "lang": "German", "interests": ["True Crime", "Spirituality"] }, 
{"user_id": 24, "lang": "English", "interests": ["Spirituality", "Business"] }, 
{"user_id": 25, "lang": "English", "interests": ["Science", "Spirituality"] }, 
{"user_id": 26, "lang": "Both", "interests": ["True Crime", "Technology", "Sports"] }, 
{"user_id": 27, "lang": "Both", "interests": ["Art", "Business"] }, 
{"user_id": 28, "lang": "German", "interests": ["Health", "Science", "Comedy"] }, 
{"user_id": 29, "lang": "German", "interests": ["Spirituality", "True Crime", "Music"] }, 
{"user_id": 30, "lang": "German", "interests": ["Spirituality", "Health", "True Crime"] }, 
{"user_id": 31, "lang": "German", "interests": ["Technology"] }, 
{"user_id": 32, "lang": "English", "interests": ["Health", "Technology"] }, 
{"user_id": 33, "lang": "German", "interests": ["Music", "Sports", "Society", "Comedy"] }, 
{"user_id": 34, "lang": "English", "interests": ["Business", "Health", "True Crime"] }, 
{"user_id": 35, "lang": "Both", "interests": ["Music", "Comedy", "Art"] }, 
{"user_id": 36, "lang": "English", "interests": ["Business"] }, 
{"user_id": 37, "lang": "English", "interests": ["Business"] }, 
{"user_id": 38, "lang": "German", "interests": ["True Crime", "Business", "Technology", "Health"] }, 
{"user_id": 39, "lang": "English", "interests": ["True Crime"] }, 
{"user_id": 40, "lang": "Both", "interests": ["Business", "Science", "Technology"] }, 
{"user_id": 41, "lang": "English", "interests": ["Sports", "Comedy", "Society"] }, 
{"user_id": 42, "lang": "German", "interests": ["Spirituality", "Technology"] }, 
{"user_id": 43, "lang": "Both", "interests": ["Art", "Spirituality", "Comedy"] }, 
{"user_id": 44, "lang": "English", "interests": ["Music", "True Crime", "Business", "Technology"] }, 
{"user_id": 45, "lang": "German", "interests": ["Art", "True Crime"] }, 
{"user_id": 46, "lang": "German", "interests": ["Business", "Science", "Spirituality"] }, 
{"user_id": 47, "lang": "German", "interests": ["Spirituality", "Art", "True Crime", "Technology"] }, 
{"user_id": 48, "lang": "German", "interests": ["Sports", "Science"] }, 
{"user_id": 49, "lang": "English", "interests": ["Science", "Technology"] }, 
{"user_id": 50, "lang": "German", "interests": ["Technology", "Business"] }, 
{"user_id": 51, "lang": "Both", "interests": ["Business"] }, 
{"user_id": 52, "lang": "Both", "interests": ["Science", "Business", "True Crime", "Music"] }, 
{"user_id": 53, "lang": "Both", "interests": ["Art", "Technology", "Comedy"] }, 
{"user_id": 54, "lang": "German", "interests": ["Art", "Science", "Spirituality"] }, 
{"user_id": 55, "lang": "German", "interests": ["Sports", "Comedy"] }, 
{"user_id": 56, "lang": "Both", "interests": ["Music"] }, 
{"user_id": 57, "lang": "German", "interests": ["Sports", "Music", "Comedy", "Health"] }, 
{"user_id": 58, "lang": "English", "interests": ["Health", "Sports", "Art"] }, 
{"user_id": 59, "lang": "English", "interests": ["Health", "Music"] }, 
{"user_id": 60, "lang": "German", "interests": ["Society"] }, 
{"user_id": 61, "lang": "Both", "interests": ["Society"] }, 
{"user_id": 62, "lang": "Both", "interests": ["Society", "Music"] }, 
{"user_id": 63, "lang": "English", "interests": ["Health", "Spirituality", "Art"] }, 
{"user_id": 64, "lang": "English", "interests": ["Business", "Health"] }, 
{"user_id": 65, "lang": "English", "interests": ["Health", "Comedy", "Technology"] }, 
{"user_id": 66, "lang": "Both", "interests": ["Comedy", "Spirituality", "Technology"] }, 
{"user_id": 67, "lang": "German", "interests": ["Spirituality"] }, 
{"user_id": 68, "lang": "English", "interests": ["Art", "Comedy", "Spirituality"] }, 
{"user_id": 69, "lang": "English", "interests": ["Sports", "Technology"] }, 
{"user_id": 70, "lang": "Both", "interests": ["Art", "Spirituality"] }, 
{"user_id": 71, "lang": "English", "interests": ["Comedy", "Society"] }, 
{"user_id": 72, "lang": "German", "interests": ["Music", "Technology", "Health", "Society"] }, 
{"user_id": 73, "lang": "Both", "interests": ["Spirituality", "Comedy", "Sports"] }, 
{"user_id": 74, "lang": "German", "interests": ["Technology", "Art"] }, 
{"user_id": 75, "lang": "Both", "interests": ["Spirituality"] }, 
{"user_id": 76, "lang": "German", "interests": ["Health", "Sports"] }, 
{"user_id": 77, "lang": "Both", "interests": ["Comedy", "True Crime", "Sports"] }, 
{"user_id": 78, "lang": "Both", "interests": ["Society", "Technology", "Spirituality"] }, 
{"user_id": 79, "lang": "English", "interests": ["Comedy", "Society"] }, 
{"user_id": 80, "lang": "Both", "interests": ["Comedy", "Spirituality", "Business"] }, 
{"user_id": 81, "lang": "English", "interests": ["Spirituality"] }, 
{"user_id": 82, "lang": "English", "interests": ["Health", "Society", "Technology"] }, 
{"user_id": 83, "lang": "Both", "interests": ["Sports", "Science", "Society", "Business"] }, 
{"user_id": 84, "lang": "English", "interests": ["True Crime", "Science", "Music"] }, 
{"user_id": 85, "lang": "Both", "interests": ["Health", "Business", "True Crime"] }, 
{"user_id": 86, "lang": "Both", "interests": ["Health", "Spirituality", "Society", "Art"] }, 
{"user_id": 87, "lang": "German", "interests": ["Spirituality", "Art", "Comedy"] }, 
{"user_id": 88, "lang": "German", "interests": ["Art", "Music"] }, 
{"user_id": 89, "lang": "English", "interests": ["True Crime", "Spirituality"] }, 
{"user_id": 90, "lang": "German", "interests": ["True Crime", "Spirituality", "Sports"] }, 
{"user_id": 91, "lang": "German", "interests": ["Sports"] }, 
{"user_id": 92, "lang": "English", "interests": ["True Crime", "Science", "Art"] }, 
{"user_id": 93, "lang": "German", "interests": ["Society"] }, 
{"user_id": 94, "lang": "German", "interests": ["Business"] }, 
{"user_id": 95, "lang": "German", "interests": ["Comedy", "Science", "Sports"] }, 
{"user_id": 96, "lang": "German", "interests": ["Comedy"] }, 
{"user_id": 97, "lang": "German", "interests": ["Science", "Comedy", "Music"] }, 
{"user_id": 98, "lang": "English", "interests": ["Business", "Music", "Health", "Science"] }, 
{"user_id": 99, "lang": "English", "interests": ["Spirituality", "Sports"] }, 
{"user_id": 100, "lang": "Both", "interests": ["True Crime", "Technology", "Society", "Sports"] }, 
{"user_id": 101, "lang": "German", "interests": ["Science", "Society", "Sports", "True Crime"] }, 
{"user_id": 102, "lang": "Both", "interests": ["Health", "Society", "Sports", "Art"] }, 
{"user_id": 103, "lang": "Both", "interests": ["Spirituality", "Society"] }, 
{"user_id": 104, "lang": "German", "interests": ["Technology", "Spirituality"] }, 
{"user_id": 105, "lang": "Both", "interests": ["Health", "Society", "Sports"] }, 
{"user_id": 106, "lang": "English", "interests": ["Art", "Technology"] }, 
{"user_id": 107, "lang": "German", "interests": ["Technology", "Business", "Spirituality"] }, 
{"user_id": 108, "lang": "German", "interests": ["Art", "True Crime"] }, 
{"user_id": 109, "lang": "Both", "interests": ["Business", "Music"] }, 
{"user_id": 110, "lang": "German", "interests": ["Comedy", "Technology"] }, 
{"user_id": 111, "lang": "Both", "interests": ["Science", "Sports", "True Crime", "Technology"] }, 
{"user_id": 112, "lang": "German", "interests": ["Science", "Comedy", "Technology", "Society"] }, 
{"user_id": 113, "lang": "Both", "interests": ["Health", "Spirituality"] }, 
{"user_id": 114, "lang": "Both", "interests": ["Technology", "Society", "Art", "True Crime"] }, 
{"user_id": 115, "lang": "Both", "interests": ["Spirituality", "Technology", "Art"] }, 
{"user_id": 116, "lang": "German", "interests": ["Society", "Music"] }, 
{"user_id": 117, "lang": "Both", "interests": ["Society", "Science"] }, 
{"user_id": 118, "lang": "Both", "interests": ["Spirituality", "Health", "Society", "Science", "Business"] }, 
{"user_id": 119, "lang": "German", "interests": ["Art"] }, 
{"user_id": 120, "lang": "Both", "interests": ["Spirituality", "Music"] }, 
{"user_id": 121, "lang": "English", "interests": ["Sports", "Society", "Spirituality"] }, 
{"user_id": 122, "lang": "German", "interests": ["True Crime", "Comedy", "Sports", "Health"] }, 
{"user_id": 123, "lang": "English", "interests": ["Comedy", "Health", "Spirituality", "True Crime"] }, 
{"user_id": 124, "lang": "Both", "interests": ["Spirituality", "Society"] }, 
{"user_id": 125, "lang": "German", "interests": ["Spirituality", "Music", "Health"] }, 
{"user_id": 126, "lang": "Both", "interests": ["Art", "Comedy", "Technology", "Society"] }, 
{"user_id": 127, "lang": "English", "interests": ["Business", "Sports", "True Crime"] }, 
{"user_id": 128, "lang": "German", "interests": ["Science", "Sports"] }, 
{"user_id": 129, "lang": "English", "interests": ["Comedy", "True Crime", "Art"] }, 
{"user_id": 130, "lang": "English", "interests": ["Music", "Spirituality", "Art", "Society"] }, 
{"user_id": 131, "lang": "Both", "interests": ["Music", "True Crime", "Art"] }, 
{"user_id": 132, "lang": "German", "interests": ["Comedy", "Sports", "Art"] }, 
{"user_id": 133, "lang": "German", "interests": ["Business", "Sports", "Comedy"] }, 
{"user_id": 134, "lang": "Both", "interests": ["Science", "Spirituality", "Business"] }, 
{"user_id": 135, "lang": "Both", "interests": ["Comedy"] }, 
{"user_id": 136, "lang": "German", "interests": ["Spirituality", "Music", "True Crime"] }, 
{"user_id": 137, "lang": "Both", "interests": ["Society", "Art", "Music"] }, 
{"user_id": 138, "lang": "English", "interests": ["Music", "Spirituality"] }, 
{"user_id": 139, "lang": "German", "interests": ["Sports", "Spirituality", "Business"] }, 
{"user_id": 140, "lang": "Both", "interests": ["Health"] }, 
{"user_id": 141, "lang": "Both", "interests": ["Society", "Science"] }, 
{"user_id": 142, "lang": "English", "interests": ["Health", "Science", "Sports"] }, 
{"user_id": 143, "lang": "Both", "interests": ["Art", "Science"] }, 
{"user_id": 144, "lang": "Both", "interests": ["Science", "Business"] }, 
{"user_id": 145, "lang": "German", "interests": ["Art", "True Crime", "Business"] }, 
{"user_id": 146, "lang": "English", "interests": ["Art", "Music"] }, 
{"user_id": 147, "lang": "German", "interests": ["Art", "True Crime", "Technology"] }, 
{"user_id": 148, "lang": "English", "interests": ["Music", "Sports"] }, 
{"user_id": 149, "lang": "German", "interests": ["Society", "Science", "True Crime", "Spirituality"] }, 
{"user_id": 150, "lang": "Both", "interests": ["Society", "True Crime", "Music", "Technology"] }, 
{"user_id": 151, "lang": "German", "interests": ["Science", "Business"] }, 
{"user_id": 152, "lang": "German", "interests": ["Health", "Music"] }, 
{"user_id": 153, "lang": "German", "interests": ["Science", "Technology", "Art"] }, 
{"user_id": 154, "lang": "English", "interests": ["Comedy", "Business", "Health"] }, 
{"user_id": 155, "lang": "German", "interests": ["True Crime", "Society", "Technology", "Business"] }, 
{"user_id": 156, "lang": "Both", "interests": ["Spirituality", "Technology", "Comedy"] }, 
{"user_id": 157, "lang": "Both", "interests": ["Sports", "Society", "Science"] }, 
{"user_id": 158, "lang": "English", "interests": ["Science", "Music"] }, 
{"user_id": 159, "lang": "English", "interests": ["Music"] }, 
{"user_id": 160, "lang": "Both", "interests": ["Society", "Technology", "Sports"] }, 
{"user_id": 161, "lang": "Both", "interests": ["Art", "Health"] }, 
{"user_id": 162, "lang": "German", "interests": ["Science", "Art", "True Crime"] }, 
{"user_id": 163, "lang": "English", "interests": ["True Crime", "Society", "Comedy"] }, 
{"user_id": 164, "lang": "English", "interests": ["Spirituality", "Comedy"] }, 
{"user_id": 165, "lang": "English", "interests": ["Sports", "Business"] }, 
{"user_id": 166, "lang": "Both", "interests": ["Society"] }, 
{"user_id": 167, "lang": "English", "interests": ["Business", "Art", "True Crime"] }, 
{"user_id": 168, "lang": "Both", "interests": ["Comedy", "Science", "Health", "Technology"] }, 
{"user_id": 169, "lang": "Both", "interests": ["Comedy"] }, 
{"user_id": 170, "lang": "English", "interests": ["Sports", "Art", "Spirituality"] }, 
{"user_id": 171, "lang": "Both", "interests": ["Art", "Sports"] }, 
{"user_id": 172, "lang": "Both", "interests": ["True Crime", "Sports", "Technology"] }, 
{"user_id": 173, "lang": "German", "interests": ["Sports", "Art", "Society"] }, 
{"user_id": 174, "lang": "English", "interests": ["Comedy", "Music"] }, 
{"user_id": 175, "lang": "German", "interests": ["Science", "Health", "Technology"] }, 
{"user_id": 176, "lang": "English", "interests": ["Health"] }, 
{"user_id": 177, "lang": "English", "interests": ["True Crime", "Society"] }, 
{"user_id": 178, "lang": "German", "interests": ["Health", "Art", "Society", "Science"] }, 
{"user_id": 179, "lang": "German", "interests": ["Science", "Music"] },]

for i in range(0, 180):
    user_id = i
    language_pref = random.choice(languages)
    user_interests = []
    for j in range(0, min(len(interests), max(1, int(random.gauss(3, 1))))):
        while True:
            candidate = '"{}"'.format(random.choice(interests))
            if candidate not in user_interests:
                user_interests.append(candidate)
                break
    print('{{"user_id": {}, "lang": "{}", "interests": [{}] }}, '.format(user_id, language_pref, ", ".join(user_interests)))
    
    
# Spotify Request an die Daten